# Generated by Django 5.2.13 on 2026-05-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_align_transactions_with_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
